### ISSUE TITLE
Add MacPorts Reference Entry in Getting Started

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#921]
From @JustinProminic 

> Please add a line item to the Getting Started specifically for MacPorts:
> https://www.macports.org/install.php
> 
> It is necessary on Mac to have MacPorts to get at least:
> - emacs-app
> - svn
> 
> probably other things in the future... especially if we add some custom C/C++ code that may need to be compiled as part of our own projects that we have not yet ported to GitHub and made sure it can compile inside our development environment.   
> 
> Also, having MacPorts explicitly listed in Getting Started would help us remember to NOT recommend Homebrew anymore, and to make all of our recommendation install text be focused on MacPorts for things like svn and emacs-app.

**Comment by rat-moonshine** [comment]
**Updates:**

1. New settings entry for MacPorts
2. Showing up an entry in Getting Started
3. An entry in About section

While testing MacPorts version using `port version` (https://trac.macports.org/wiki/UsingMacPortsQuickStart), console throws following _NativeProcess_ error:
```
: sqlite error: attempt to write a readonly database (8) while executing query: UPDATE registry.metadata SET value = '1.205' WHERE key = 'version'
:     while executing
: "registry::open $db_path"
:     (procedure "mportinit" line 712)
:     invoked from within
: "mportinit ui_options global_options global_variations"
: Error: /opt/local/bin/port: Failed to initialize MacPorts, sqlite error: attempt to write a readonly database (8) while executing query: UPDATE registry.metadata SET value = '1.205' WHERE key = 'version'
```
I confirm if I run the same command on Terminal, also received the same output. 

Currently, About section is not printing any version number of MacPorts.

**To-Do:**
I assume MacPorts is available only on macOS, so I need to figure-out following adjustments:
1. Not showing MacPorts entry in MSDKI when running on Windows
2. Not adding MacPorts in Moonshine settings when running on Windows
3. Not showing MacPorts in About (should get fixed with 1)

**Comment by rat-moonshine** [comment]
Commit references referring into wrong issue:
https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/commit/b817990bb02b294fcd816c96e759981471c54914
https://github.com/Moonshine-IDE/Moonshine-IDE/commit/5da9ceb73e07eb13e1ac0ded0c43972de4d31cb8

**Comment by rat-moonshine** [comment]
Updates:

- [x] Not showing MacPorts entry in MSDKI when running on Windows
- [x] Not adding MacPorts in Moonshine settings when running on Windows
- [x] Not showing MacPorts in About (should get fixed with 1)

Note: Default macPort path detection/setup (`/opt/local/bin`) currently happens only on non-sandbox build. Since this path will not available until bookmarking on sandbox.

**Comment by JoelProminic** [comment]
I tested the branch build, and I saw that Moonshine set the default path as I expected automatically.

However it does not show as configured in Getting Started or About:
![image](https://user-images.githubusercontent.com/24532731/148819671-2c075bde-f828-4ce3-969f-8ab8693a54ad.png)

Note that Vagrant also does not show that it is configured properly in Getting Started, but it does show a version on the About page:
![image](https://user-images.githubusercontent.com/24532731/148819813-c929825e-bbbb-4c30-8fe1-ec1b03564aed.png)

I tried changing the MacPorts setting manually, but that didn't make a difference for the configuration status.

**Comment by rat-moonshine** [comment]
> However it does not show as configured in Getting Started or About:

I incorporated detection and update to Getting Started, for Vagrant and MacPorts. Please, check.

**Comment by JoelProminic** [comment]
I tested with branch build 69, and I am now seeing both the warnings and green checkboxes for Vagrant and MacPorts.  The user needs to manually install these tools for now, but I'm thinking we shouldn't show the warning if they are configured already.

![image](https://user-images.githubusercontent.com/24532731/149010168-9972c9d8-56c4-42db-b40c-3ff72935009d.png)

I don't get the same errors you reported for `port version`.  I think you need to check your MacPorts installation or reinstall.

    % port version
    Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
    Version: 2.7.1

I still see that MacPorts shows as "Not Installed" in the About page.  Is the implementation still pending while you resolve the `port version` error?

**Comment by rat-moonshine** [comment]
> The user needs to manually install these tools for now, but I'm thinking we shouldn't show the warning if they are configured already.

Usually, any item that is not download-able the warning is shown. I adjusted this to not to show when runs in Moonshine. 

> Is the implementation still pending while you resolve the port version error?

Having a re-install of MacPorts clears the problem for me. When the addition of MacPorts version check already added into the codes, I stopped the command from execution since it was throwing error and terminates the process. I restored version check command to run for MacPorts. I confirm, the version is showing correctly now.

**Comment by JoelProminic** [comment]
I'm seeing the version properly now for MacPorts in the About page.

I'm still seeing  a warning for the configured MacPorts (and Vagrant, SVN, and Git).  I don't think this matches the original design for SVN and Git.  We can discuss this more in the meeting today.

**Comment by rat-moonshine** [comment]
I adjusted repeaters in MSDKI to not to show warning icon/message if the item is already downloaded.

I also encountered the error that @JoelProminic reported earlier - this now rectified:

> I'm seeing an error when I open the SVN Settings page:
> : Error #1034
> : TypeError: Error #1034
> : at actionScripts.plugins.svn::SVNPlugin/onSDKPathSelected()
> : at flash.events::EventDispatcher/dispatchEvent()
> : at actionScripts.plugin.settings.renderers::PathRenderer/onPathRendererCreationComplete()
> : at actionScripts.plugin.settings.renderers::PathRenderer/___PathRenderer_VGroup1_creationComplete()
> : at flash.events::EventDispatcher/dispatchEvent()
> : at mx.core::UIComponent/dispatchEvent()
> : at mx.core::UIComponent/set initialized()
> : at mx.managers::LayoutManager/validateClient()
> : at mx.core::UIComponent/validateNow()
> : at actionScripts.plugin.settings::SettingsView/buildSettings()
> : at actionScripts.plugin.settings::SettingsView/handleItemClick()
> : at flash.events::EventDispatcher/dispatchEvent()
> : at mx.core::UIComponent/dispatchEvent()
> : at spark.components::List/commitSelection()
> : at spark.components.supportClasses::ListBase/commitProperties()
> : at spark.components::List/commitProperties()
> : at mx.core::UIComponent/validateProperties()
> : at spark.components::List/item_mouseDownHandler()
> : at flash.events::EventDispatcher/dispatchEvent()
> : at mx.core::UIComponent/dispatchEvent()
> : at mx.managers::SystemManager/mouseEventHandler() :
> : Click here to Report a Bug

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`. Please, starts testing using regular Development build.

**Comment by JoelProminic** [comment]
When I tested with the merged build today, I saw that the MacPorts installation was not detected at the default location (`/opt/local/bin/port`).  I remember that this was detected properly in my tests earlier this week.  I saw the same problem in the MSDKI branch build.

**Comment by rat-moonshine** [comment]
MacPorts detection should be fixed now, please check.

**Comment by JoelProminic** [comment]
Detection looks fine now.
